# Deployment file for the book-catalog and inventory-management microservices 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: project3.azurecr.io/book_catalog:1 
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://miranda_pena_carrasquillo:UewJJu68xtuyTYJxairzvyZNl4UlVFqy@dpg-cr9qj40gph6c73d42bm0-a.singapore-postgres.render.com/library_db_l7q6"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: project3.azurecr.io/inventory_management:1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://miranda_pena_carrasquillo:UewJJu68xtuyTYJxairzvyZNl4UlVFqy@dpg-cr9qj40gph6c73d42bm0-a.singapore-postgres.render.com/library_db_l7q6"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer